---
  # Required credentials settings
  chartmogul:
    accountToken: ""
    secretKey: ""
  zuora:
    username: ""
    password: ""
    production: true
  # Optional settings
  cancellation:
    # Unpaid invoices due more than x months are considered canceled.
    unpaidToCancelMonths: 2
    # Subscriptions that didn't get a renewal invoice in under x months are canceled
    # after their term.
    noRenewalToCancelMonths: 2
  # Filtering on transformation & CM settings besides credentials
  transformer:
    # Default: false = don't load customers unless they have at least one non-zero non-free invoiced subscription
    includeFree: false
    # Name of data source in ChartMogul
    dataSource: "Zuora-00"
    # Filtering of customer accounts - useful if you want to test or need to omit some problematic ones.
    # accounts:
    #   exclude:
    #     - ""
    #   include:
    #     - ""
  # Optional configuration if you'll be using export
  export:
    mongo:
      url: "mongodb://localhost:21017/db"
      collections:
        # Names of collections to which different export data will be saved
        activities: "cmActivities"
        all: "cmAll"
        mrr: "cmMrr"
        subscriptions: "cmSubscriptions"

  # Global settings for logger, see log4js documentation. Modules are tagged, eg. "zuora", "itemsBuilder"
  log4js:
    levels:
      [all]: "DEBUG"
    appenders:
      -
        type: "console"
