---
  chartmogul:
    accountToken: ""
    secretKey: ""
  zuora:
    username: ""
    password: ""
    production: true
  transformer:
    includeFree: false
    dataSource: "Zuora-00"
    #accounts:
      exclude:
        - ""
      include:
        - ""
  log4js:
    levels:
      [all]: "DEBUG"
    appenders:
      -
        type: "console"
